# Bag Of Words --> Transferlearning
by Niels Helsø 
git = https://github.com/slein89/BOW_transferlearning  
linkedin = https://www.linkedin.com/in/nielshelsoe/

# Purpose
- 3 models for NLP
- compare
- every model have a tutorial 
- IT IS ALL ON **GIT HUB**

# Agenda
1. Introduction
2. Classifier with BoW (Bag Of Words)
3. Classifier with Word embeddings
4. Classifier with Transferlearning

## Code, articles, tutorials and stuff
Git url = https://github.com/slein89/BOW_transferlearning

# Introduction
- Who am I?
    - Name = Niels
    - Age = 29
    - Education = cand. it
    - have coded in python for 2 years time
    - Love NLP
    - Favorite guilty pleasure = paagen gifler

# The Danish Business Authority
- Government agency
- 550 people
- Goal: The best conditions and framework for Danish companies
- Three locations: Copenhagen, Silkeborg, Nykøbing Falster


## Data science in Danish Business Authority
- Data-Science team of 5 (WE ARE HIRING!)
- Use Data science 
- Profiles:
    - fine arts
    - economics
    - engineer
    - phd
    - it
    - information studies
- Using Python and libs such as:
    - sklearn
    - pandas
    - keras
    - numpy
    - and so on

# why this talk?
1. Give an overview of where natural language processing(NLP) is going and where it has been
2. Pro and cons of three differrent methods
3. Demystify NLP

# PLEASE ASK QUESTIONS 
There is no such thing as a dumb question.

# Disclaimer
Use this at your own risk

# Data 
thanks to Prayson Wilfred Daniel
- trustpilot reviews
- 254464 (after making a equal distribution of the two classes)
- task: build a sentiment classifier 

In [4]:
from src.data.load_data import load_trustpilot_data
from src.preprocessing.text_pre import clean_text
df_trust = load_trustpilot_data()
df_trust = clean_text(df_trust, 'text')
print('Total value of classes amount to')
print('-----------------')
print(df_trust['y'].value_counts())
print('')
print('Examples of text')
print('-----------------')
for index,row in df_trust[:5].iterrows():
    print(row['text'])

Amount of the to classes
-----------------
1    127232
0    127232
Name: y, dtype: int64

Examples of text
-----------------
det var iorden 
nåede sikkert og hurtigt frem det var en god oplevelse
vi har altid været glade for tryg og deres måde at håndtere forsikringssager på vi anmelder self heller ikke hvad som helst men til gengæld får vi altid en ærlig og redelig behandling uden problemer selv om tryg i perioder kan være lidt dyrere end andre forsikringsselskaber foretrækker vi dem fordi vi så heller ikke skal trækkes med diskussioner om udbetaling når uheldet er ude 
hurtig pakke lev til pakkeboksen
bestilte tøj på nettet og fik pakken hurtigere end ventet og kunne endda følge den hele vejen 


In [ ]:
# %load src/preprocessing/text_pre.py
import re
import string
def clean_text (df, row_name):
    #lower all text
    df[row_name] = df[row_name].str.lower()
    #remove all numbers
    df[row_name] = df[row_name].apply(lambda x: x.translate(str.maketrans('','','0123456789')))
    #remove all special chareters
    df[row_name] = df[row_name].apply(lambda x: re.sub('[\W]+', ' ', x))
    #make translation tabel where punctuation is removed and apply it to the text
    table = str.maketrans({key: None for key in string.punctuation})
    df[row_name] = df[row_name].apply(lambda x: x.translate(table))
    return df

# Metrics:
- Roc auc
- Confusion Matrix
- Classification report (recall, precision, F1 score)

# BoW (Bag Of Words)
- one of the first NLP approaches
- converts text to vector

## Libs for BoW in python
- Gensim
- Nltk
- Spacy
- Sklearn


In [1]:
corpus=['Pydatacopenhagen is the best place to be tonight, yes tonight',
'At Pydatacopenhagen every one is welcome']

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
#the vector representation of the words (13)
print( vectorizer.fit_transform(corpus).todense() )
#count of the uniq words in corpus
print( vectorizer.vocabulary_ )

[[0 1 1 0 1 0 1 1 1 1 2 0 1]
 [1 0 0 1 1 1 0 1 0 0 0 1 0]]
{'pydatacopenhagen': 7, 'is': 4, 'the': 8, 'best': 2, 'place': 6, 'to': 9, 'be': 1, 'tonight': 10, 'yes': 12, 'at': 0, 'every': 3, 'one': 5, 'welcome': 11}


## ngrams
- helps with preserving some meaning to the sentence

In [3]:
corpus=['Pydatacopenhagen is the best place to be tonight, yes tonight',
'At Pydatacopenhagen everyone is welcome']
from nltk import ngrams
grams = ngrams(corpus[0].split(),2)
for gram in grams:
    print (gram)

('Pydatacopenhagen', 'is')
('is', 'the')
('the', 'best')
('best', 'place')
('place', 'to')
('to', 'be')
('be', 'tonight,')
('tonight,', 'yes')
('yes', 'tonight')


In [5]:
from sklearn.model_selection import train_test_split
from src.preprocessing.metrics import get_metrics
X_train,X_test,y_train,y_test = train_test_split(df_trust['text'], df_trust['y'], random_state=42 )

### performanche on BoW
Let's take a look at a tutorial and see how BOW performs

In [7]:
from joblib import load
model_bow = load('data/models/bow_model.pkl')
get_metrics(model_bow, X_test, y_test)

roc_auc_score
0.9001972503652068
-------------------
classification_report
              precision    recall  f1-score   support

           0       0.90      0.90      0.90     31932
           1       0.90      0.90      0.90     31684

   micro avg       0.90      0.90      0.90     63616
   macro avg       0.90      0.90      0.90     63616
weighted avg       0.90      0.90      0.90     63616

-------------------
confusion_matrix
[[28623  3309]
 [ 3041 28643]]
-------------------
CPU times: user 14.6 s, sys: 237 ms, total: 14.8 s
Wall time: 14.8 s


## Some issues
- Ngrams get us some of the way with the sentiment
- just one vector per sentence (document)

# Word embeddings
- convert each word into vector
- map it into a vector space
- allows for word representations with similar meaning to have a similar representation

## Word2vec
Word2Vec has two methods:
1. CBOW
2. Skip-gram

In [2]:
from IPython.display import IFrame
IFrame("pictures/skipgra, and cbow.png", width=600, height=400)

Lets train one and have a look of how good it is at finding word similarity

In [9]:
import gensim
word2vec_model = gensim.models.Word2Vec.load("data/models/word2vec.model")
w1 = 'nokia'
word2vec_model.wv.most_similar(positive=w1)

[('lumia', 0.7854803204536438),
 ('htc', 0.7818347811698914),
 ('iphone', 0.7195836305618286),
 ('sony', 0.6978476643562317),
 ('lenovo', 0.692030668258667),
 ('huawei', 0.6810896396636963),
 ('bærbar', 0.6735221147537231),
 ('tablet', 0.6730877161026001),
 ('mobiltelefon', 0.6699701547622681),
 ('ipod', 0.6555711627006531)]

## FastText
- Framework with word2vecs cbow implemented 
  - ngrams (both on words and characters)
  - size (size of the context window)
  - dim (size of the vector)
- Each word is represented as a bag of character n-grams
    - ngrams = 3
    - where = <wh, whe, her, ere, re>

In [11]:
%%time
from src.model.fasttext import fasttext_pipeline 
X_train,X_test,y_train,y_test = train_test_split(df_trust[['text']], df_trust['y'], random_state=42 )
model_fasttext = fasttext_pipeline(X_train, y_train)
get_metrics(model_fasttext, X_test, y_test)

roc_auc_score
0.9457883754461629
-------------------
classification_report
              precision    recall  f1-score   support

           0       0.94      0.96      0.95     31932
           1       0.96      0.93      0.95     31684

   micro avg       0.95      0.95      0.95     63616
   macro avg       0.95      0.95      0.95     63616
weighted avg       0.95      0.95      0.95     63616

-------------------
confusion_matrix
[[30552  1380]
 [ 2066 29618]]
-------------------
CPU times: user 49min 20s, sys: 9.16 s, total: 49min 29s
Wall time: 4min 22s


# Transferlearning
- lets take something that we have learned somewhere and apply it to a new domain
- why this?
    - we do not always have a ton of data
    - The model do not need to learn from scratch
    - Thus we save time
    - We make (re)use of models built by very talented people
    - the approach has proven itself in computer vision

## Universal Language Model Fine-tuning for Text Classification (ULMFiT)
- fast.ai
- 15 may 2018
- Make use of Language model approach
  - A model which predicts the next word in a sentence
      - e.g. "jeg elsker pågen" -> "gifler" 
  - has high understanding of semantics
      - eg. " så det der kommer ..." != "jeg så en flot sol opgang"
  - has a high understanding of grammar
- Data = wikipedia

In [5]:
from IPython.display import IFrame
IFrame("pictures/ulmfit.png", width=600, height=200)

## Status on a Danish ulmfit model
- trained for 24 hours on Danish wikipedia
- 20000 + wikipedia articles 
- 60000 + tokens

Let's take a look at the code!

# models:
- BOW
    - 90% roc auc
- Word2vec
    - 94,5% roc auc
- Transerlearning
    - 81 % roc auc

# Recap
------------------------------------------------------
- BoW
  - pros
      - Robust towards its specific task
      - High transparecy
      - Quick to code
      - easy to install
  - cons
      - "only" counts word
      - loses semantics
      - slow to train  
------------------------------------------------------
- Word2vec(FastText)
    - pros
        - take semantics into account
        - is fast
        - easy to install 
    - cons
        - transparency is a bit of a blur
        - needs a good portion of data  
------------------------------------------------------
- Transferlearning (ULMFIT)
    - pros
        - state of the art performanche (they say)
        - have the potential to save a lot of time
    - cons
        - hard to code and install
        - initial training takes a long time
        - Black Box

# KISS
***Keep It Simple Stupid*** can be quite clever

Questions?

Thank you for your time.